export LANG=ja_JP.UTF-8
export EDITOR=nvim
export XDG_CONFIG_HOME=$HOME/.config
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export CARGO_HOME="$HOME/.cargo"
export PATH="$CARGO_HOME/bin:$PATH"
export PATH=$(go env GOPATH)/bin:$PATH
export PATH="$PATH:$HOME/.bin"
export HOMEBREW_INSTALL_CLEANUP=1
